"""add competitor_products

Revision ID: 0fa874e49474
Revises: 0013_rename_comp_name
Create Date: 2026-04-07 13:05:47.171672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa874e49474'
down_revision: Union[str, None] = '0013_rename_comp_name'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('database_type', sa.Enum('POSTGRESQL', 'MYSQL', 'SQLSERVER', 'ORACLE', 'FIREBIRD', 'SQLITE', 'SNOWFLAKE', 'CSV', 'XLSX', name='data_source_type', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', 'product_name', name='uq_competitor_product_combo')
    )
    op.create_index(op.f('ix_competitor_products_competitor_id'), 'competitor_products', ['competitor_id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked_at'), table_name='refresh_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_refresh_tokens_revoked_at'), 'refresh_tokens', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_competitor_products_competitor_id'), table_name='competitor_products')
    op.drop_table('competitor_products')
    # ### end Alembic commands ###
